Control = []
Fan = []
Temp = []
Flat = []
Linear = []
Target = []

[[CustomTemp]]
name = "CPU"
kind = "Average"
inputs = []

[[Graph]]
name = "Graph"

[[Graph.coord]]
temp = 50
percent = 30

[[Graph.coord]]
temp = 50
percent = 30
