[[Control]]
name = "pwm2 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm2"
input = "linear1"
active = true

[[Control]]
name = "pwm3 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm3"
input = "target1"
active = true

[[Control]]
name = "pwm4 nct6798-isa-0290"
id = "nct6798-isa-0290-pwm4"
input = "flat1"
active = true


[[Flat]]
name = "flat1"
value = 100

[[Linear]]
name = "linear1"
input = "CPU"
minTemp = 10
minSpeed = 10
maxTemp = 70
maxSpeed = 100



[[Target]]
name = "target1"
input = "GPU"
idleTemp = 40
idleSpeed = 10
loadTemp = 70
loadSpeed = 100




[[CustomTemp]]
name = "CPU"
kind = "Average"
inputs = [
    "TSI0_TEMP nct6798-isa-0290",
    "AUXTIN1 nct6798-isa-0290",
]

[[CustomTemp]]
name = "GPU"
kind = "Average"
inputs = [
]



[[Temp]]
name = "TSI0_TEMP nct6798-isa-0290"
id = "nct6798-isa-0290-temp11_input"

[[Temp]]
name = "AUXTIN1 nct6798-isa-0290"
id = "nct6798-isa-0290-temp4_input"

[[Temp]]
name = "Tctl k10temp-pci-00c3"
id = "k10temp-pci-00c3-temp1_input"

[[Temp]]
name = "Tccd1 k10temp-pci-00c3"
id = "k10temp-pci-00c3-temp3_input"

[[Temp]]
name = "Composite nvme-pci-0100"
id = "nvme-pci-0100-temp1_input"


[[Fan]]
name = "fan2 nct6798-isa-0290"
id = "nct6798-isa-0290-fan2_input"

[[Fan]]
name = "fan3 nct6798-isa-0290"
id = "nct6798-isa-0290-fan3_input"

[[Fan]]
name = "fan4 nct6798-isa-0290"
id = "nct6798-isa-0290-fan4_input"
